version: '3.8'

networks:
  GLOBAL_NETWORK:
    external: true

#-------------------------------------------
# Единый блок environment (якорь)
#-------------------------------------------
x-common-env: &common_env
  INFISICAL_HOST: ${INFISICAL_HOST}
  INFISICAL_TOKEN: ${INFISICAL_TOKEN}
  ENVIRONMENT_SLUG: ${ENVIRONMENT_SLUG}

services:

  panel:
    build: ./
    container_name: admin-panel
    command: poetry run daphne -b 0.0.0.0 -p 8000 PANEL.asgi:application --verbosity 0
    environment: *common_env
    restart: always
    ports:
      - '8091:8000'
    volumes:
      - /root/logs/PANEL/panel:/code/logs/
    networks:
      - GLOBAL_NETWORK

  celery:
    build: ./
    container_name: panel-celery-tasks
    command: poetry run celery -A PANEL worker --beat -l INFO
    environment: *common_env
    restart: always
    depends_on:
      - panel
    volumes:
      - /root/logs/PANEL/celery:/code/logs/
    networks:
      - GLOBAL_NETWORK

  beat:
    build: ./
    container_name: panel-beat
    command: poetry run celery -A PANEL beat -S django_celery_beat.schedulers:DatabaseScheduler --loglevel=info
    environment: *common_env
    restart: always
    depends_on:
      - panel
    volumes:
      - /root/logs/PANEL/beat:/code/logs/
    networks:
      - GLOBAL_NETWORK
